data:
    file_path: "output/preprocessed_mp3d/data_gt60_noRE.pkl"
    type: "heterogeneous"

run_control:
    num_runs: 10
    early_stop_window: 600

network:
    conv_block: 'GAT_edge'
    dropout: 0.2
    GAT_hidden_dims: [64, 64]
    GAT_heads: [5, 5, 5]
    GAT_concats: [False, False, False]

optimization:
    lr: 0.001
    num_epochs: 800
    weight_decay: 0.001
    batch_size: 2048

logger:
    output_dir: "output/log_mp3d/data_gt60_noW_noRE"
