data:
    file_path: "output/preprocessed_mp3d/htree_filter2.pkl"
    type: "neural_tree"

run_control:
    num_runs: 1
    early_stop_window: 300

network:
    conv_block: 'GAT_edge'
    hidden_dim: 32
    num_layers: 2
    dropout: 0.25
    GAT_hidden_dims: [4]
    GAT_heads: [4, 4]
    GAT_concats: [True, False]

optimization:
    lr: 0.001
    num_epochs: 200
    weight_decay: 0.0001
    batch_size: 2048

logger:
    output_dir: "output/log_test/debug_htree"
