data:
    file_path: "output/preprocessed_Stanford3DSG/data_nt.pkl"
    type: "heterogeneous"

run_control:
    num_runs: 5
    early_stop_window: 400

network:
    conv_block: 'GAT'
    hidden_dim: 128
    num_layers: 2
    dropout: 0.25
    GAT_hidden_dims: [128, 128]
    GAT_heads: [6, 6]
    GAT_concats: [True, True]

optimization:
    lr: 0.001
    num_epochs: 800
    weight_decay: 0.0001
    batch_size: 512

logger:
    output_dir: "output/log_test/debug"
