data:
    file_path: "output/preprocessed_Stanford3DSG/data_nt.pkl"
    type: "homogeneous"

run_control:
    num_runs: 100
    early_stop_window: -1

network:
    conv_block: 'GIN'
    hidden_dim: 64
    num_layers: 3
    dropout: 0.25

optimization:
    lr: 0.005
    num_epochs: 1000
    weight_decay: 0.001
    batch_size: 512

logger:
    output_dir: "output/log_Stanford_final/baseline_GIN"
