data:
    file_path: "output/preprocessed_Stanford3DSG/htree_nt.pkl"
    type: "homogeneous"

run_control:
    num_runs: 100
    early_stop_window: -1

network:
    disable_initialization: True
    conv_block: 'GAT'
    dropout: 0.25
    GAT_hidden_dims: [128, 128, 128, 128]
    GAT_heads: [6, 6, 6, 6]
    GAT_concats: [True, True, True, True]

optimization:
    lr: 0.0005
    num_epochs: 1000
    weight_decay: 0.0001
    batch_size: 128

logger:
    output_dir: "output/log_Stanford/htree_GAT"
